[main]
exclude=abrt-cli appstream-data at bc chrony crontabs cyrus-sasl-plain deltarpm dos2unix dracut-config-rescue fuzzel grubby initial-setup* iptstate kernel-debug* mcelog mtr PackageKit PackageKit-glib pinfo plocate psacct qemu-user-static realmd rsyslog* setroubleshoot setroubleshoot-plugins setroubleshoot-server sos sssd*
